use [TRAINING_DB]
go

CREATE TABLE T_PC_ROLE (
 ROLE_ID VARCHAR(32) NOT NULL,
 ROLE_NAME NVARCHAR(64),
 ROLE_DESCRIPTION CHAR(10)
);

ALTER TABLE T_PC_ROLE ADD CONSTRAINT PK_T_PC_ROLE PRIMARY KEY (ROLE_ID);


CREATE TABLE T_COMPUTER_TERMINAL (
 COM_TERMINAL_ID VARCHAR(64) NOT NULL,
 COM_TERMINAL_NAME VARCHAR(64)
);

ALTER TABLE T_COMPUTER_TERMINAL ADD CONSTRAINT PK_T_COMPUTER_TERMINAL PRIMARY KEY (COM_TERMINAL_ID);


CREATE TABLE T_GENDER (
 GENDER_ID INT NOT NULL,
 GENDER_NAME NVARCHAR(50)
);

ALTER TABLE T_GENDER ADD CONSTRAINT PK_T_GENDER PRIMARY KEY (GENDER_ID);


CREATE TABLE T_EMPLOYEE (
 EMPLOYEE_ID VARCHAR(32) NOT NULL,
 EMPLOYEE_NAME NVARCHAR(50),
 BIRTH_DAY DATE,
 GENDER_ID INT NOT NULL,
 CELLPHONE_NO VARCHAR(16),
 MOBILE_MAIL VARCHAR(64),
 PC_MAIL VARCHAR(64)
);

ALTER TABLE T_EMPLOYEE ADD CONSTRAINT PK_T_EMPLOYEE PRIMARY KEY (EMPLOYEE_ID);


CREATE TABLE T_DEPARTMENT (
 DEPARTMENT_ID VARCHAR(32) NOT NULL,
 DEPARTMENT_NAME NVARCHAR(50),
 TELEPHONE_NO VARCHAR(16)
);

ALTER TABLE T_DEPARTMENT ADD CONSTRAINT PK_T_DEPARTMENT PRIMARY KEY (DEPARTMENT_ID);


CREATE TABLE T_DEPARTMENT_EMPLOYEE (
 DEPARTMENT_ID VARCHAR(32) NOT NULL,
 EMPLOYEE_ID VARCHAR(32) NOT NULL
);

ALTER TABLE T_DEPARTMENT_EMPLOYEE ADD CONSTRAINT PK_T_DEPARTMENT_EMPLOYEE PRIMARY KEY (DEPARTMENT_ID,EMPLOYEE_ID);


CREATE TABLE T_CUSTOMER_CORP (
 CUSTOMER_CORP_ID VARCHAR(32) NOT NULL,
 CUSTOMER_CORP_NAME NVARCHAR(128)
);

ALTER TABLE T_CUSTOMER_CORP ADD CONSTRAINT PK_T_CUSTOMER_CORP PRIMARY KEY (CUSTOMER_CORP_ID);


CREATE TABLE T_CUSTOMER_PART (
 CUSTOMER_CORP_ID VARCHAR(32) NOT NULL,
 CUSTOMER_PART_ID VARCHAR(32) NOT NULL,
 CUSTOMER_PART_NAME NVARCHAR(128)
);

ALTER TABLE T_CUSTOMER_PART ADD CONSTRAINT PK_T_CUSTOMER_PART PRIMARY KEY (CUSTOMER_CORP_ID,CUSTOMER_PART_ID);


CREATE TABLE T_PC_ACCOUNT (
 EMPLOYEE_ID VARCHAR(32) NOT NULL,
 COM_TERMINAL_ID VARCHAR(64) NOT NULL,
 LOGIN_ID VARCHAR(64),
 PASS_WORD VARCHAR(64)
);

ALTER TABLE T_PC_ACCOUNT ADD CONSTRAINT PK_T_PC_ACCOUNT PRIMARY KEY (EMPLOYEE_ID,COM_TERMINAL_ID);


CREATE TABLE T_PC_ACCOUNT_ROLE (
 EMPLOYEE_ID VARCHAR(32) NOT NULL,
 COM_TERMINAL_ID VARCHAR(64) NOT NULL,
 ROLE_ID VARCHAR(32) NOT NULL
);

ALTER TABLE T_PC_ACCOUNT_ROLE ADD CONSTRAINT PK_T_PC_ACCOUNT_ROLE PRIMARY KEY (EMPLOYEE_ID,COM_TERMINAL_ID,ROLE_ID);


CREATE TABLE T_ORDER_HEADER (
 ORDER_ID VARCHAR(32) NOT NULL,
 CUSTOMER_CORP_ID VARCHAR(32) NOT NULL,
 CUSTOMER_PART_ID VARCHAR(32) NOT NULL,
 ORDER_TITLE NVARCHAR(128)
);

ALTER TABLE T_ORDER_HEADER ADD CONSTRAINT PK_T_ORDER_HEADER PRIMARY KEY (ORDER_ID);


CREATE TABLE T_PRODUCT_CATEGORY (
 PRODUCT_CATEGORY_ID VARCHAR(32) NOT NULL,
 PRODUCT_CATEGORY_NAME NVARCHAR(64),
 DEPARTMENT_ID VARCHAR(32)
);

ALTER TABLE T_PRODUCT_CATEGORY ADD CONSTRAINT PK_T_PRODUCT_CATEGORY PRIMARY KEY (PRODUCT_CATEGORY_ID);


CREATE TABLE T_PRODUCT_ITEM (
 PRODUCT_ITEM_ID VARCHAR(64) NOT NULL,
 PRODUCT_ITEM_NAME NVARCHAR(128),
 UNIT_PRICE INT,
 PRODUCT_CATEGORY_ID VARCHAR(32)
);

ALTER TABLE T_PRODUCT_ITEM ADD CONSTRAINT PK_T_PRODUCT_ITEM PRIMARY KEY (PRODUCT_ITEM_ID);


CREATE TABLE T_PROJECT (
 PROJECT_ID VARCHAR(32) NOT NULL,
 PROJECT_NAME NVARCHAR(128),
 ORDER_ID VARCHAR(32)
);

ALTER TABLE T_PROJECT ADD CONSTRAINT PK_T_PROJECT PRIMARY KEY (PROJECT_ID);


CREATE TABLE T_ORDER_DETAIL (
 ORDER_ID VARCHAR(32) NOT NULL,
 ORDER_ITEM_NO INT NOT NULL,
 PRODUCT_ITEM_ID VARCHAR(64),
 ORDER_ITEM_NAME NVARCHAR(128),
 QUANTITY INT,
 UNIT_PRICE INT
);

ALTER TABLE T_ORDER_DETAIL ADD CONSTRAINT PK_T_ORDER_DETAIL PRIMARY KEY (ORDER_ID,ORDER_ITEM_NO);


CREATE TABLE T_EMP_ATTEND_TIME (
 EMPLOYEE_ID VARCHAR(32) NOT NULL,
 WORK_DATE DATE NOT NULL,
 SEQ DATE NOT NULL,
 START_TIME DATETIME,
 END_TIME DATETIME,
 NOTE NVARCHAR(256),
 PROJECT_ID VARCHAR(32)
);

ALTER TABLE T_EMP_ATTEND_TIME ADD CONSTRAINT PK_T_EMP_ATTEND_TIME PRIMARY KEY (EMPLOYEE_ID,WORK_DATE,SEQ);


ALTER TABLE T_EMPLOYEE ADD CONSTRAINT FK_T_EMPLOYEE_0 FOREIGN KEY (GENDER_ID) REFERENCES T_GENDER (GENDER_ID);


ALTER TABLE T_DEPARTMENT_EMPLOYEE ADD CONSTRAINT FK_T_DEPARTMENT_EMPLOYEE_0 FOREIGN KEY (DEPARTMENT_ID) REFERENCES T_DEPARTMENT (DEPARTMENT_ID);
ALTER TABLE T_DEPARTMENT_EMPLOYEE ADD CONSTRAINT FK_T_DEPARTMENT_EMPLOYEE_1 FOREIGN KEY (EMPLOYEE_ID) REFERENCES T_EMPLOYEE (EMPLOYEE_ID);


ALTER TABLE T_CUSTOMER_PART ADD CONSTRAINT FK_T_CUSTOMER_PART_0 FOREIGN KEY (CUSTOMER_CORP_ID) REFERENCES T_CUSTOMER_CORP (CUSTOMER_CORP_ID);


ALTER TABLE T_PC_ACCOUNT ADD CONSTRAINT FK_T_PC_ACCOUNT_0 FOREIGN KEY (EMPLOYEE_ID) REFERENCES T_EMPLOYEE (EMPLOYEE_ID);
ALTER TABLE T_PC_ACCOUNT ADD CONSTRAINT FK_T_PC_ACCOUNT_1 FOREIGN KEY (COM_TERMINAL_ID) REFERENCES T_COMPUTER_TERMINAL (COM_TERMINAL_ID);


ALTER TABLE T_PC_ACCOUNT_ROLE ADD CONSTRAINT FK_T_PC_ACCOUNT_ROLE_0 FOREIGN KEY (EMPLOYEE_ID,COM_TERMINAL_ID) REFERENCES T_PC_ACCOUNT (EMPLOYEE_ID,COM_TERMINAL_ID);
ALTER TABLE T_PC_ACCOUNT_ROLE ADD CONSTRAINT FK_T_PC_ACCOUNT_ROLE_1 FOREIGN KEY (ROLE_ID) REFERENCES T_PC_ROLE (ROLE_ID);


ALTER TABLE T_ORDER_HEADER ADD CONSTRAINT FK_T_ORDER_HEADER_0 FOREIGN KEY (CUSTOMER_CORP_ID,CUSTOMER_PART_ID) REFERENCES T_CUSTOMER_PART (CUSTOMER_CORP_ID,CUSTOMER_PART_ID);


ALTER TABLE T_PRODUCT_CATEGORY ADD CONSTRAINT FK_T_PRODUCT_CATEGORY_0 FOREIGN KEY (DEPARTMENT_ID) REFERENCES T_DEPARTMENT (DEPARTMENT_ID);


ALTER TABLE T_PRODUCT_ITEM ADD CONSTRAINT FK_T_PRODUCT_ITEM_0 FOREIGN KEY (PRODUCT_CATEGORY_ID) REFERENCES T_PRODUCT_CATEGORY (PRODUCT_CATEGORY_ID);


ALTER TABLE T_PROJECT ADD CONSTRAINT FK_T_PROJECT_0 FOREIGN KEY (ORDER_ID) REFERENCES T_ORDER_HEADER (ORDER_ID);


ALTER TABLE T_ORDER_DETAIL ADD CONSTRAINT FK_T_ORDER_DETAIL_0 FOREIGN KEY (ORDER_ID) REFERENCES T_ORDER_HEADER (ORDER_ID);
ALTER TABLE T_ORDER_DETAIL ADD CONSTRAINT FK_T_ORDER_DETAIL_1 FOREIGN KEY (PRODUCT_ITEM_ID) REFERENCES T_PRODUCT_ITEM (PRODUCT_ITEM_ID);


ALTER TABLE T_EMP_ATTEND_TIME ADD CONSTRAINT FK_T_EMP_ATTEND_TIME_0 FOREIGN KEY (EMPLOYEE_ID) REFERENCES T_EMPLOYEE (EMPLOYEE_ID);
ALTER TABLE T_EMP_ATTEND_TIME ADD CONSTRAINT FK_T_EMP_ATTEND_TIME_1 FOREIGN KEY (PROJECT_ID) REFERENCES T_PROJECT (PROJECT_ID);


